### ISSUE TITLE
dataset_info.json file missing in ORM preprocessed data

### ISSUE THREAD

**Issue by sarvghotra** [KbsdJames/MATH-Minos#3]
ORM data is missing dataset_info.json file:

> data-00000-of-00001.arrow
state.json

So, it's causing the following error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "miniforge3/envs/adv_verif/lib/python3.10/site-packages/datasets/load.py", line 2160, in load_from_disk
    raise FileNotFoundError(
FileNotFoundError: Directory data/math_minos_nl_reward/Math-shepherd-adapted/math-shepherd-orm_preprocessed/train/ is neither a `Dataset` directory nor a `DatasetDict` directory.

**Comment by sarvghotra** [comment]
@KbsdJames A gentle ping : )

**Comment by KbsdJames** [comment]
> @KbsdJames A gentle ping : )

Apologies for the delayed response! We're on it and will supplement this soon.
